version: "3"
services:
  pfa-laravel:
    build: .
    container_name: pfa-laravel
    entrypoint: dockerize -wait tcp://pfa-mysql:3306 -timeout 20s php-fpm
    volumes:
      - ./:/var/www
      - /var/www/vendor
    depends_on:
      - pfa-mysql
    networks:
      - pfa-nginx-laravel
      - pfa-laravel-mysql

  pfa-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    container_name: pfa-mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "./dbdata:/var/lib/mysql"
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: pfa-laravel
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - pfa-laravel-mysql

  pfa-ngnix:
    build: ./.docker/nginx
    restart: always
    container_name: pfa-ngnix
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - pfa-laravel
    networks:
      - pfa-nginx-laravel

networks:
  pfa-nginx-laravel:
    driver: bridge
  pfa-laravel-mysql:
    driver: bridge
